version: '3.9'

services:
  # Gateway
  gateway:
    build: ./gateway
    env_file:
      - ./gateway/.env
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - post-service
      - comment-service

  # User Service
  user-service:
    build: ./services/user-service
    env_file:
      - ./services/user-service/.env
    ports:
      - "4001:4001"
    depends_on:
      - user-mongo

  user-mongo:
    image: mongo:6
    volumes:
      - user-data:/data/db
    ports:
      - "27017:27017"

  # Post Service
  post-service:
    build: ./services/post-service
    env_file:
      - ./services/post-service/.env
    ports:
      - "4002:4002"
    depends_on:
      - post-mongo
      - user-service

  post-mongo:
    image: mongo:6
    volumes:
      - post-data:/data/db
    ports:
      - "27018:27017"

  # Comment Service
  comment-service:
    build: ./services/comment-service
    env_file:
      - ./services/comment-service/.env
    ports:
      - "4003:4003"
    depends_on:
      - comment-mongo
      - user-service
      - post-service

  comment-mongo:
    image: mongo:6
    volumes:
      - comment-data:/data/db
    ports:
      - "27019:27017"

  # Auth Service
  auth-service:
    build: ./services/auth-service
    env_file:
      - ./services/auth-service/.env
    ports:
      - "4004:4004"
    depends_on:
      - auth-mongo

  auth-mongo:
    image: mongo:6
    volumes:
      - auth-data:/data/db
    ports:
      - "27020:27017"

volumes:
  user-data:
  post-data:
  comment-data:
  auth-data: